// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var YogaLayout = require("yoga-layout");

function create(attrs) {
  var __node = YogaLayout.Node.create();
  __node.setWidth(attrs[/* width */0]);
  __node.setHeight(attrs[/* height */1]);
  __node.setJustifyContent(attrs[/* justify_content */2]);
  __node.setAlignItems(attrs[/* align_items */4]);
  __node.setFlexDirection(attrs[/* flex_direction */3]);
  return /* record */[
          /* __t */__node,
          /* attrs */attrs
        ];
}

function insertChild(child, index, node) {
  node[/* __t */0].insertChild(child[/* __t */0], index);
  return node;
}

function calculateLayout(ctx, node) {
  node[/* __t */0].calculateLayout(ctx[/* width */0], ctx[/* height */1], ctx[/* direction */2]);
  return node;
}

function computedLayout(node) {
  var cl = node[/* __t */0].getComputedLayout();
  return /* record */[
          /* left */cl.left,
          /* top */cl.top,
          /* width */cl.width,
          /* height */cl.height
        ];
}

var Node = /* module */[
  /* create */create,
  /* insertChild */insertChild,
  /* calculateLayout */calculateLayout,
  /* computedLayout */computedLayout
];

function $less$less$neg(root, param) {
  return insertChild(param[0], param[1], root);
}

function $star$great(node, ctx) {
  return computedLayout(calculateLayout(ctx, node));
}

var Operators = /* module */[
  /* <<- */$less$less$neg,
  /* *> */$star$great
];

exports.Node = Node;
exports.Operators = Operators;
/* yoga-layout Not a pure module */
